### ISSUE TITLE
[BE]이미지 저장 구현

### ISSUE THREAD

**Issue by kimgun95** [walkingWithPuppy/walkingWith7Puppy#22]
- [x] 이미지 저장 방법 확인
- 이미지 저장에 [FE]문의 결과 base64 인코딩된 데이터가 아닌 이미지 파일을 넘겨주기로 함
- Multipart 사용
- [x] S3 버킷 생성하기
- [x] S3에 이미지 올리기 테스트
- [x] S3에 올린 이미지 조회하기
- [x] S3이미지 수정, 삭제하기

**Comment by Cho-woo-pil** [comment]
Multipart를 이용한 이미지저장방법 확인 및 S3 버킷생성 완료
